name: action_notes
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider:
  intl: ^0.19.0
  easy_localization: ^3.0.0
  table_calendar: ^3.1.2
  sqflite: ^2.3.3+2
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.2.3
  flutter_timezone: ^3.0.1
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.52
  shared_preferences: ^2.3.2
  reorderables: ^0.6.0
  device_info_plus: ^11.1.0
  permission_handler: ^11.3.1
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/translations/
    - assets/images/Edit.png
    - assets/images/Plus.png
    - assets/images/Home.png
    - assets/images/Calendar.png
    - assets/images/Setting.png
    - assets/images/ar_back.png
    - assets/images/Filter.png
    - assets/images/Folder.png
    - assets/images/Chart.png
    - assets/images/Chart1.png
    - assets/images/Chart2.png
    - assets/images/Chart3.png
    - assets/images/Folder2.png
    - assets/images/Upload.png
    - assets/images/arr_left.png
    - assets/images/arr_right.png
    - assets/images/arr_vn.png
    - assets/images/krest.png
    - assets/images/menu.png
    - assets/images/Check.png

